version: '3.8'

services:
  db:
    image: mongo
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017

  db_admin:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_PORT=27017
    expose:
      - 8081
    ports:
      - 8081:8081
    depends_on:
      - db